### ISSUE TITLE
Always return 1 exit code for unzip

### ISSUE THREAD

**Issue by jhen0409** [GPMDP/electron-devtools-installer#1]
https://github.com/GPMDP/electron-devtools-installer/blob/master/index.js#L25

I used `forceDownload`, unzip always callback error, but actually unzip success.

**Comment by MarshallOfSound** [comment]
Ahh, this will be a folder overwrite error, I'll fix it shortly :)

**Comment by MarshallOfSound** [comment]
@jhen0409 It might be worth pointing out that React Dev tools doesn't work in any Electron version above `1.2.1`

See #6101

**Comment by jhen0409** [comment]
Looks `fs.mkdirSync` cannot remove not empty folder, should use [rimraf](https://github.com/isaacs/rimraf) instead?

**Comment by MarshallOfSound** [comment]
@jhen0409 My bad 😆 I tested with an empty folder 😢 

I'll be setting up test suites for this shortly anyway 👍

**Comment by MarshallOfSound** [comment]
@jhen0409 New version published with rimraf
