### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by xwvvvvwx** [GPMDP/electron-devtools-installer#17]
I am setting up an electron boilerplate for personal use (see [here](https://github.com/xwvvvvwx/typescript-boilerplate/tree/devtools)), and when I try to use `electron-devtools-installer` I see the following errors in my webpack build output:

https://gist.github.com/xwvvvvwx/e7e895fb1614fedd362b4d82cc377239

I am calling `electron-devtools-installer` in my [index.tsx](https://github.com/xwvvvvwx/typescript-boilerplate/blob/devtools/src/index.tsx) 

Am I doing something wrong?

**Comment by MarshallOfSound** [comment]
> Am I doing something wrong?

Yes 😆 

I'm not too familiar with webpack but you need to configure it to accept `electron` and node built ins as global modules that it doesn't have to pack

**Comment by xwvvvvwx** [comment]
Thanks ;)

Adding the following to my webpack config fixed the errors :)

```
...
  target: 'electron-renderer',
  externals: {
        "7zip": "7zip"
  },
...
```
