### ISSUE TITLE
Any way to add Redux Devtools?

### ISSUE THREAD

**Issue by LestaD** [GPMDP/electron-devtools-installer#3]
https://github.com/zalmoxisus/redux-devtools-extension

**Comment by MarshallOfSound** [comment]
Have you tried using the ID `lmhkpmbekcpmknklioeibfkpmmfibljd` in the install method

**Comment by LestaD** [comment]
#4

**Comment by MarshallOfSound** [comment]
Published in `1.1.3`

**Comment by LestaD** [comment]
:+1:
