### ISSUE TITLE
Extension name is returned as undefined (Vue)

### ISSUE THREAD

**Issue by citycide** [GPMDP/electron-devtools-installer#5]
`installExtension`'s promise resolution returns `name` as undefined, at least for the Vue devtools. This is on the latest 1.1.4 installer / 1.2.4 electron combo, using the exported Vue ID method.

I'm not entirely sure why either, electron returns it from `addDevToolsExtension` which pulls it from the extension's manifest.json name field. I checked the manifest and it has a valid name field, also confirmed by the fact that electron will log a message `Attempted to load extension "Vue.js devtools" that has already been loaded.` so it does have the name.

My guess is it either has something to do with async which I'm very new to, or that `addDevToolsExtension` returns differently depending on context ( remote or not ).

Recreate:

```javascript
import installExtension, { VUEJS_DEVTOOLS } from 'electron-devtools-installer';

installExtension(VUEJS_DEVTOOLS)
  .then(name => console.log(`Added Extension:  ${name}`));

// -> Added Extension: undefined
```

**Comment by MarshallOfSound** [comment]
Is this from the main process or the renderer process?

**Comment by MarshallOfSound** [comment]
Also, although it returns undefined, does it correctly add the extension?

**Comment by citycide** [comment]
Main process, and it adds the extension just fine.

**Comment by MarshallOfSound** [comment]
I can't replicate the undefined issue.

```js
// This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  app.on('ready', () => {
    installExtension.default(installExtension.VUEJS_DEVTOOLS)
      .then((name) => {
        console.log('Added: ', name);
        mainWindow = new BrowserWindow();
        mainWindow.openDevTools();

        mainWindow.center();

        // and load the index.html of the app.
        mainWindow.loadURL(`http://todomvc.com/examples/react`);

        // Emitted when the window is closed.
        mainWindow.on('closed', () => {
          // Dereference the window object, usually you would store windows
          // in an array if your app supports multi windows, this is the time
          // when you should delete the corresponding element.
          mainWindow = null;
        });
      })
      .catch((err) => console.log('An error occurred: ', err));
  });
```

Can you post minimum sample code that causes the issue

**Comment by citycide** [comment]
Sure I'll try to narrow it down when I get some time.

**Comment by MarshallOfSound** [comment]
@citycide Any update on this?

**Comment by MarshallOfSound** [comment]
Closing due to lack of response / updates
