### ISSUE TITLE
Peer dependency on "electron-prebuilt" is not necessary?

### ISSUE THREAD

**Issue by teleclimber** [GPMDP/electron-devtools-installer#8]
Hi, I don't use npm to load my Electron binaries. This package requires that I do. But when I simply ignore the warnings everything seems to work fine.

If the dependency doesn't add anything it should probably be eliminated.

Thanks!

**Comment by MarshallOfSound** [comment]
@teleclimber The peer-dependency is there mainly to indicate to people using NPM to install `electron-prebuilt`, the minimum version of electron they need for this tool to work.

Installing electron from outside NPM is a rare occurence and as you say, you can just ignore the warnings 😆

**Comment by teleclimber** [comment]
Seems it would be more appropriate to programmatically check against the version of electron that is running, and throw a warning if not ok.

**Comment by MarshallOfSound** [comment]
@teleclimber You are correct 😆 

It's not normal that you can just query the dependent version 😄
